Repository PCL-Community/PCL2-CE, pull requests merged in 2024-12, with the labels that each got.

#5 feat: MyHint 的三态
  Plain Craft Launcher 2/Controls/MyHint.xaml.vb
Labels: · 新功能, - 等待合并

#6 feat: 资源收藏
  Plain Craft Launcher 2/Controls/MyListItem.xaml
  Plain Craft Launcher 2/Controls/MyListItem.xaml.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/MyCompItem.xaml.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: · 新功能, - 等待合并

#4 Quilt 支持
  Plain Craft Launcher 2/Controls/MyCard.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Images/Blocks/Quilt.png
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMod.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadMod.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadPack.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadQuilt.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadQuilt.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml
  Plain Craft Launcher 2/Pages/PageSelectRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionOverall.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionOverall.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
  Plain Craft Launcher 2/Resources/Custom.xaml
Labels: √ 完成, · 新功能

#3 [Feature] LittleSkin OAuth 登录支持
  .github/workflows/build.yml
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageLaunch/MyMsgLogin.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginAuth.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
Labels: √ 完成, · 新功能

#9 支持下载资源包
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadResourcePack.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadResourcePack.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: √ 完成, · 新功能

#10 支持下载光影包
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/MyCompItem.xaml.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadShader.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadShader.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: ⇵ 正在处理, · 新功能

#11 fix: 错误修复
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
Labels: · Bug, ⇲ 等待合并

#15 feat: 复刻远古反馈页面
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherFeedback.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherFeedback.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherVote.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherVote.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: √ 完成, · 新功能

#20 修改版本信息中的 Commit Hash 为前 7 位
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml.vb
Labels: ⇵ 正在处理, · 优化

#24 fix: issue #19
  Plain Craft Launcher 2/Pages/PageLaunch/MyMsgLogin.xaml.vb
Labels: · Bug

#21 feat: 框架升级
  .github/workflows/build.yml
  Plain Craft Launcher 2/App.config
  Plain Craft Launcher 2/FodyWeavers.xml
  Plain Craft Launcher 2/FodyWeavers.xsd
  Plain Craft Launcher 2/My Project/Resources.Designer.vb
  Plain Craft Launcher 2/My Project/Resources.resx
  Plain Craft Launcher 2/My Project/Settings.Designer.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
  Plain Craft Launcher 2/Resources/Imazen.WebP.dll
  Plain Craft Launcher 2/Resources/NAudio.dll
  Plain Craft Launcher 2/Resources/Newtonsoft.Json.dll
  Plain Craft Launcher 2/Resources/Ookii.Dialogs.Wpf.dll
  Plain Craft Launcher 2/packages.config
Labels: · 优化, ⇲ 等待合并

#27 Fix 按下下载新 Mod 按钮可能导致启动器崩溃
  Plain Craft Launcher 2/FormMain.xaml.vb
Labels: √ 完成, · Bug

#28 fix: 修改了部分过时文本
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
Labels: ⇵ 正在处理, · Bug

#30 Add Support for littleskin OAuth Login
  .github/workflows/build.yml
Labels: √ 完成, · 优化

#29 feat: 下载自定义文件
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
Labels: ⇵ 正在处理, · 新功能

#33 fix: 更新相关内容
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/My Project/AssemblyInfo.vb
Labels: √ 完成, · Bug

#34 feat: 清理游戏垃圾
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
Labels: · 新功能, ⇲ 等待合并

#36 简化版本页面，并使“查看源代码”精确到commit
  .github/workflows/build.yml
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml
Labels: ⇵ 正在处理, · 优化

#35 新功能：识别码
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: ⇵ 正在处理, · 新功能

#37 feat: 添加在标题栏上的社区版标识
  Plain Craft Launcher 2/FormMain.xaml
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
Labels: ⇵ 正在处理, · 新功能

#38 加入网络测试能力
  Plain Craft Launcher 2/FormMain.xaml
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/ModLink.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkHiper.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkHiper.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLeft.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkNetStatus.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkNetStatus.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLink.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
  Plain Craft Launcher 2/packages.config
Labels: · 新功能, ⇲ 等待合并

#39 允许隐藏社区版提示
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
Labels: · 优化, ⇲ 等待合并
