Repository PCL-Community/PCL2-CE, pull requests merged in 2025-01, with the labels that each got.

#41 fix: 语言标记
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: √ 完成, · Bug

#42 Feat:当配置使用 HTTP 协议的认证服务器给予用户警告
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml.vb
Labels: √ 完成, · 新功能

#40 修改崩溃时跳转的反馈页面为PCL2-CE的页面
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
Labels: ⇵ 正在处理, · 优化

#43 feat: Proxy
  Plain Craft Launcher 2/Controls/MyImage.vb
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
Labels: · 新功能, ⇲ 等待合并

#45 同步联机代码
  Plain Craft Launcher 2/Controls/MyPageRight.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/ModLink.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkFeedback.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkIoi.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkIoi.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLeft.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkNetStatus.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLink.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLink.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionLeft.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: · 新功能, ⇲ 等待合并

#47 修复新功能投票 URL 中斜杠重复的问题
  Plain Craft Launcher 2/Pages/PageOther/PageOtherVote.xaml.vb
Labels: · Bug, ⇲ 等待合并

#49 放弃对 Windows 10 以下版本系统的支持
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/My Project/AssemblyInfo.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
  Plain Craft Launcher 2/packages.config
Labels: · 新功能, ⇲ 等待合并

#65 修改 Issues 模板
  .github/ISSUE_TEMPLATE/bug1.yml
  .github/ISSUE_TEMPLATE/bug2.yml
  .github/ISSUE_TEMPLATE/bug9.yml
  .github/ISSUE_TEMPLATE/ch.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: ⇵ 正在处理, · 优化

#69 Fix:指向的链接为 4.6.2 的离线安装程序
  Plain Craft Launcher 2/Application.xaml.vb
Labels: · Bug, ⇲ 等待合并

#72 fix: text not disappear
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
Labels: · Bug, ⇲ 等待合并

#75 Fix #61
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionScreenshot.xaml.vb
Labels: · Bug, ⇲ 等待合并

#85 默认开启 SSL 验证
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
Labels: √ 完成, · 优化

#73 fix: update fail
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: · Bug, ⇲ 等待合并

#82 faet: async image load
  Plain Craft Launcher 2/Modules/Base/MyBitmap.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionScreenshot.xaml.vb
Labels: · 优化, ⇲ 等待合并

#74 添加禁用 Java Wrapper 的选项
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml.vb
Labels: · 新功能, ⇲ 等待合并

#90 识别剪贴板资源并提示跳转
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModWatcher.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
Labels: √ 完成, · 新功能

#83 添加 Java 细致搜索开关
  Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
Labels: √ 完成, · 优化, ! 破坏性

#98 feat: resource save auto locate
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
Labels: √ 完成, · 优化

#93 feat: disable theme select
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
Labels: · 优化, ⇲ 等待合并

#110 bump: 2.9.5
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/My Project/AssemblyInfo.vb
Labels: √ 完成

#105 feat: try decouple
  Plain Craft Launcher 2/Controls/MyCard.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadForge.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLiteLoader.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadNeoForge.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadOptiFine.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherHelp.xaml.vb
  Plain Craft Launcher 2/Pages/PageSelectRight.xaml.vb
Labels: ⇵ 正在处理, · 优化, ! 破坏性

#112 fix: update replace file name incorrect
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: · Bug, ⇲ 等待合并

#109 feat: Allow to open together with the official version
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/FormMain.xaml
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/My Project/AssemblyInfo.vb
Labels: · 优化, ⇲ 等待合并

#68 feat: allow disable hardware acceleration
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModAnimation.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
Labels: ⇵ 正在处理, · 新功能

#118 fix: drag file not apply
  Plain Craft Launcher 2/FormMain.xaml.vb
Labels: · Bug, ⇲ 等待合并

#86 Java 优先使用高性能 GPU 启动
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: √ 完成, · 新功能

#48 系统 SMTC 控件支持
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/ModMusic.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: · 新功能, ⇲ 等待合并, ! 破坏性

#52 feat: change target framework
  Plain Craft Launcher 2/App.config
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: √ 完成, · 新功能, ! 破坏性

#50 [Sync] update code
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
  Plain Craft Launcher 2/Modules/Minecraft/MyLocalModItem.xaml.vb
  Plain Craft Launcher 2/Modules/ModDevelop.vb
  Plain Craft Launcher 2/My Project/AssemblyInfo.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginLegacy.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml.vb
  Plain Craft Launcher 2/Resources/Help.zip
  Plain Craft Launcher 2/app.manifest
Labels: · 新功能, / 等待前置

#125 feat: 深色模式
  Plain Craft Launcher 2/Application.xaml
  Plain Craft Launcher 2/Controls/MyButton.xaml
  Plain Craft Launcher 2/Controls/MyCard.vb
  Plain Craft Launcher 2/Controls/MyCheckBox.xaml
  Plain Craft Launcher 2/Controls/MyIconButton.xaml.vb
  Plain Craft Launcher 2/Controls/MyMsg/MyMsgInput.xaml
  Plain Craft Launcher 2/Controls/MyMsg/MyMsgSelect.xaml
  Plain Craft Launcher 2/Controls/MyMsg/MyMsgText.xaml
  Plain Craft Launcher 2/Controls/MyRadioBox.xaml
  Plain Craft Launcher 2/Controls/MyRadioButton.xaml
  Plain Craft Launcher 2/Controls/MySlider.xaml
  Plain Craft Launcher 2/FormMain.xaml
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageLaunch/MyMsgLogin.xaml
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
Labels: ⇵ 正在处理, · 新功能

#128 支持 unlisted-versions-of-minecraft
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
Labels: ⇵ 正在处理, · 新功能, ! 破坏性

#132 chore:移除 ClientToken & 代码解耦合
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: √ 完成, · 优化

#135 Remove LittleSkin OAuth
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 👌 完成, · Bug, ❗ 破坏性

#150 fix: logic error
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionResourcePack.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionScreenshot.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionShader.xaml.vb
Labels: · Bug, 🕑 等待合并

#153 chore: addition msg output
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionResourcePack.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionShader.xaml.vb
Labels: 👌 完成, · Bug

#154 fix: 深色模式 #4
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: · Bug, 🕑 等待合并

#164 fix: #163
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
Labels: 🕑 等待合并
