Repository PCL-Community/PCL2-CE, pull requests merged in 2025-10, with the labels that each got.

#1605 fix: 修复自动切换中文低版本不起效
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 🕑 等待合并, size: M

#1624 perf(comp): 异步执行本地资源加载的耗时操作
  Plain Craft Launcher 2/Controls/MyImage.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Pages/PageInstance/MyLocalModItem.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceCompResource.xaml.vb
Labels: 🕑 等待合并, size: L

#1613 fix(launch): 修复部分 MMC 整合包无法启动的问题
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
Labels: 🕑 等待合并, size: XS

#1620 imp(link): 优化联机设置 UI 并清理代码
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkSetup.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkSetup.xaml.vb
Labels: 🕑 等待合并, size: S

#1585 fix(link): 下载联机组件可能导致控件意外激活
  Plain Craft Launcher 2/Modules/ModLink.vb
Labels: 🕑 等待合并

#1623 feat(instance): 将实例列表中的实例信息改为 Tag 形式
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Pages/PageSelectRight.xaml.vb
Labels: 🕑 等待合并, size: M

#1619 feat(download): 修改 Mod Loader 手动安装包下载逻辑
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml.vb
Labels: 🕑 等待合并, size: L

#1625 fix(link): 修复一个意外的 ET 文件检测
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml.vb
Labels: 🕑 等待合并, size: XS

#1631 imp: 优化部分文本
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
Labels: 🕑 等待合并, size: XS

#1644 fix: 移除 On Error Resume Next
  Plain Craft Launcher 2/Controls/MyMsg/MyMsgInput.xaml.vb
  Plain Craft Launcher 2/Controls/MyMsg/MyMsgMarkdown.xaml.vb
  Plain Craft Launcher 2/Controls/MyMsg/MyMsgSelect.xaml.vb
  Plain Craft Launcher 2/Controls/MyMsg/MyMsgText.xaml.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/Base/ModValidate.vb
  Plain Craft Launcher 2/Pages/PageLaunch/MyMsgLogin.xaml.vb
Labels: 🕑 等待合并, size: M

#1651 fix(comp): 修复 CurseForge 搜索排序不生效的问题
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml.vb
Labels: 🕑 等待合并, size: XS

#1659 fix: 修复未有游戏启动时清理垃圾出现错误的提示
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
Labels: 🕑 等待合并, size: S

#1652 bump: 2.13.3
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🛠️ 等待审查, size: S

#1668 feat(launch): 支持添加自定义 Classpath 头部以用于高级调试
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSetup.xaml
Labels: 🕑 等待合并, size: S
