Repository PCL-Community/PCL2-CE, pull requests merged in 2025-07, with the labels that each got.

#980 feat(Update): 支持增量更新
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModProfile.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Modules/Updates/IUpdateSource.vb
  Plain Craft Launcher 2/Modules/Updates/UpdateInfoModel.vb
  Plain Craft Launcher 2/Modules/Updates/UpdatesMinioModel.vb
  Plain Craft Launcher 2/Modules/Updates/UpdatesMirrorChyanModel.vb
  Plain Craft Launcher 2/Modules/Updates/UpdatesRandomModel.vb
  Plain Craft Launcher 2/Modules/Updates/UpdatesWrapperModel.vb
  Plain Craft Launcher 2/Modules/Updates/VersionAnnouncementDataModel.vb
  Plain Craft Launcher 2/Modules/Updates/VersionDataModel.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🕑 等待合并

#992 fix(Comp): 错误的文件路径
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml.vb
Labels: 🕑 等待合并

#821 feat: 可选的各种蓝色
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
Labels: 🕑 等待合并

#1014 feat: 支持锁定窗口大小
  Plain Craft Launcher 2/Controls/MyResizer.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
Labels: 🕑 等待合并

#1030 fix(authlib): 去除请求体中包含的错误的参数，并在部分弹窗上加入详细的错误信息
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 🕑 等待合并

#1029 fix(Update): 通过 MirrorChyan 获取更新信息时可能出错
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Modules/Updates/UpdatesMirrorChyanModel.vb
Labels: 🕑 等待合并

#1052 fix(link): 修复联机设置自定义节点输入字符崩溃的问题
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLink.xaml
Labels: 🕑 等待合并

#1059 fix(HomePageMarket):主页市场滚动条偏左
  Plain Craft Launcher 2/Pages/PageSetup/PageHomePageMarket.xaml
Labels: 🕑 等待合并

#1058 feat(下载): 为自定义下载添加 User-Agent 支持#1041
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/My Project/Settings.Designer.vb
  Plain Craft Launcher 2/My Project/Settings.settings
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
Labels: 🚧 正在处理

#1115 feat(launch): 支持切换使用 java.exe 而不是 javaw.exe 启动游戏
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
Labels: 🕑 等待合并

#1132 feat(test): 添加创建快捷方式按钮
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
Labels: ⭕ 等待处理

#1146 refactor(rpc): 替换过时的工具调用
  Plain Craft Launcher 2/Modules/Base/ModNativeInterop.vb
Labels: 🕑 等待合并

#1197 优化用户名打码逻辑
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
Labels: 🕑 等待合并

#1204 feat(LocalComp): 自动识别资源包图标
  Plain Craft Launcher 2/Modules/Minecraft/ModLocalComp.vb
Labels: 🕑 等待合并

#1193 feat(theme): 支持自定义灰阶配置
  Plain Craft Launcher 2/Controls/MyHint.xaml.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: 🕑 等待合并

#1200 fix(CompResource): 修复启动器全选收藏和分享所选Bug
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceCompResource.xaml.vb
Labels: 🕑 等待合并

#1209 fix(theme): 修复窗体加载初期的 MyButton 空指针异常
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: 🕑 等待合并

#1210 fix(SavesInfo): 修复1.4版本以下存档信息获取出错
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSaves/PageInstanceSavesInfo.xaml
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSaves/PageInstanceSavesInfo.xaml.vb
Labels: 🕑 等待合并

#1178 fix(Crash): 修复错误报告导出中启动器日志命名不正确的问题
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
  Plain Craft Launcher 2/Resources/oauth-complete.html
Labels: 🕑 等待合并

#1208 fix(ModProfile): 修复在启动游戏前切换档案会导致档案没切过来
  Plain Craft Launcher 2/Modules/Minecraft/ModProfile.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfile.xaml.vb
Labels: 🕑 等待合并

#1228 perf(CompResource): 优化模组排序性能
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceCompResource.xaml.vb
Labels: 🕑 等待合并
