Repository PCL-Community/PCL2-CE, pull requests merged in 2025-05, with the labels that each got.

#528 fix: 不能正确读取 Cleanroom 版本信息
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
Labels: 🕑 等待合并

#529 fix: 无法正常安装核心
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
Labels: 🕑 等待合并

#390 refactor: 全局档案管理系统
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Controls/MyListItem.xaml.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModProfile.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchLeft.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginAuth.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginAuth.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginAuthSkin.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginAuthSkin.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginLegacy.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginLegacy.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginMs.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginMs.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginMsSkin.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginMsSkin.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginNide.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginNide.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginNideSkin.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginNideSkin.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfile.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfile.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfileSkin.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfileSkin.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkIoi.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionOverall.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🕑 等待合并, ❗ 破坏性

#547 fix: 深色模式 #11
  Plain Craft Launcher 2/Controls/MyRadioButton.xaml.vb
  Plain Craft Launcher 2/FormMain.xaml
Labels: 🕑 等待合并

#544 fix: 遇到无法加载的字体不应当崩溃
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
Labels: 🕑 等待合并

#545 chore: 修改文案
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml.vb
Labels: 🕑 等待合并

#541 refactor: 重新构建更新及公告系统
  .github/workflows/build.yml
  .github/workflows/pre-release-build.yml
  .github/workflows/release-build.yml
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
Labels: 🕑 等待合并

#509 feat: LabyMod 下载与启动适配
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Images/Blocks/LabyMod.png
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/My Project/Resources.Designer.vb
  Plain Craft Launcher 2/My Project/Resources.resx
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLabyMod.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLabyMod.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionLeft.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
  Plain Craft Launcher 2/Resources/linkd.exe
Labels: 🚧 正在处理, ❗ 破坏性

#585 feat: 支持在实时日志界面导出游戏运行栈
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModWatcher.vb
  Plain Craft Launcher 2/Pages/PageLogRight.xaml
  Plain Craft Launcher 2/Pages/PageLogRight.xaml.vb
Labels: ⭕ 等待处理

#584 refactor: 换用 HttpClient
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Controls/MyImage.vb
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Modules/Reference/CookieWebClient.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🕑 等待合并

#599 feat: 错误报告加入独立的环境与启动信息
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: 🕑 等待合并

#600 用户档案相关改进
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModProfile.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
Labels: 🕑 等待合并

#608 fix(Profile): 可能在请求失败时崩溃
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModProfile.vb
Labels: 🚧 正在处理

#606 加入可选的软硬件调查选项
  .github/workflows/build.yml
  .github/workflows/pre-release-build.yml
  .github/workflows/release-build.yml
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/ModEvent.vb
  Plain Craft Launcher 2/Modules/ModLink.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🕑 等待合并

#609 fix: 标题栏靠左可能崩溃
  Plain Craft Launcher 2/FormMain.xaml.vb
Labels: 🕑 等待合并

#607 feat: 支持简单查询 Minecraft 服务器
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModStyle.vb
  Plain Craft Launcher 2/Modules/ModLink.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🕑 等待合并

#627 feat: 修改资源下载界面 UI
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageComp.xaml
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageComp.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadCompDetail.xaml
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadCompDetail.xaml.vb
Labels: 🕑 等待合并

#629 fix: 自动进服选项无效
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 🕑 等待合并

#635 fix: 档案描述错误
  Plain Craft Launcher 2/Modules/Minecraft/ModProfile.vb
Labels: 🕑 等待合并

#636 perf: 优化环境问题的表述文本
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
Labels: 🕑 等待合并

#649 fix: Quilt 安装失败
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
Labels: 🕑 等待合并

#647 fix: 可能由于数据同步不及时导致的字典数据缺失
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml.vb
Labels: 🕑 等待合并

#648 fix: 存档是否可快速启动可能检查失败
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionWorld.xaml.vb
Labels: 🕑 等待合并

#651 feat: 允许取消强制要求高性能显卡
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
Labels: 🕑 等待合并

#670 为下载页面的labymod添加图标(这次应该不会有怪东西了)
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
Labels: 👌 完成

#662 fix: 由于 ThemeChanged 事件没有解除绑定导致的内存泄露
  Plain Craft Launcher 2/Controls/MyCard.vb
  Plain Craft Launcher 2/Controls/MyHint.xaml.vb
Labels: 🕑 等待合并

#676 fix: 当配置文件出现错误后启动器无法正常使用
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
Labels: 🕑 等待合并

#673 fix: 第三方登录失败
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 🕑 等待合并

#687 ci: add mirrorchyan uploading
  .github/workflows/mirrorchyan_release_note.yml
  .github/workflows/mirrorchyan_uploading.yml
  .github/workflows/pre-release-build.yml
  .github/workflows/release-build.yml
Labels: 🕑 等待合并

#691 fix: 可能无法查询到部分服务器
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
Labels: 🕑 等待合并

#690 feat: 接入 Mirror 酱
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Modules/Updates/AnnouncementDataModel.vb
  Plain Craft Launcher 2/Modules/Updates/EnumUpdateChannel.vb
  Plain Craft Launcher 2/Modules/Updates/IUpdateSource.vb
  Plain Craft Launcher 2/Modules/Updates/UpdateInfoModel.vb
  Plain Craft Launcher 2/Modules/Updates/UpdatesMinioModel.vb
  Plain Craft Launcher 2/Modules/Updates/UpdatesMirrorChyanModel.vb
  Plain Craft Launcher 2/Modules/Updates/VersionDataModel.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🕑 等待合并

#645 档案功能修复与优化
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModProfile.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchLeft.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfile.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfileSkin.xaml
Labels: 🕑 等待合并

#682 feat: 自动选中已经存在的 Fabric API 和 QSL
  Plain Craft Launcher 2/Modules/Minecraft/ModLocalComp.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionInstall.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionInstall.xaml.vb
Labels: 🕑 等待合并

#695 正版验证出错提示更换设备代码流
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: 🕑 等待合并

#707 隐藏“导入导出设置”按钮
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
Labels: 🕑 等待合并

#711 fix: 第三方登录启动失败
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 🕑 等待合并

#712 当用户试图更改第三方验证档案的披风时将其引导到皮肤站内修改
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfileSkin.xaml.vb
Labels: 👌 完成

#714 fix: LabyMod 的各种修复
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionInstall.xaml.vb
Labels: 🕑 等待合并

#722 fix: 部分字段没有使用 McLoginType 枚举值
  Plain Craft Launcher 2/Modules/Minecraft/ModProfile.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfileSkin.xaml.vb
Labels: 🕑 等待合并

#718 fix: SMTC 的一些问题
  Plain Craft Launcher 2/Modules/ModMusic.vb
Labels: 🕑 等待合并

#729 feat: 加入新的更新源
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Modules/Updates/UpdateInfoModel.vb
  Plain Craft Launcher 2/Modules/Updates/UpdatesMinioModel.vb
  Plain Craft Launcher 2/Modules/Updates/UpdatesRandomModel.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🕑 等待合并
