Repository PCL-Community/PCL2-CE, pull requests merged in 2025-06, with the labels that each got.

#760 feat: 瞅眼服务器延迟测试和 UI 改善
  Plain Craft Launcher 2/Modules/ModLink.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
Labels: 🕑 等待合并

#788 fix:没有与官方版本帮助库隔离导致官方版加载部分帮助库时出错
  Plain Craft Launcher 2/Modules/ModMain.vb
Labels: 🕑 等待合并

#789 feat: 使用系统默认图片查看器打开截图
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionScreenshot.xaml.vb
Labels: 🕑 等待合并

#794 fix: 修改玩家名功能无法使用
  Plain Craft Launcher 2/Modules/Minecraft/ModProfile.vb
Labels: ⭕ 等待处理

#774 feat: 基于管道通信的 RPC 服务和部分 RPC 功能
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModNativeInterop.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModWatcher.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🕑 等待合并

#752 feat(realtime-log): 添加实时日志保留行数设置
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Pages/PageLogLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageLogRight.xaml
  Plain Craft Launcher 2/Pages/PageLogRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
Labels: 🕑 等待合并

#805 fix: 可能因为输入地址无效导致登陆失败
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginAuth.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginAuth.xaml.vb
Labels: 🕑 等待合并

#816 feat: 档案选择页面滚动条
  Plain Craft Launcher 2/Controls/MyListItem.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfile.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfile.xaml.vb
Labels: 🕑 等待合并

#815 fix: 长于当前收藏夹的选项名显示不完整
  Plain Craft Launcher 2/Controls/MyComboBox.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
Labels: 🕑 等待合并

#825 chore:降低日志等级
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
Labels: 🕑 等待合并

#847 feat:添加今日人品
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
Labels: 🕑 等待合并

#866 chore(translate): 为暂时没有译文的情况给予正确提示
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
Labels: 🕑 等待合并

#830 fix: 关闭 Minecraft 无效
  Plain Craft Launcher 2/Modules/Minecraft/ModWatcher.vb
Labels: 🕑 等待合并

#882 feat:为修改正版玩家名添加警告
  Plain Craft Launcher 2/Modules/Minecraft/ModProfile.vb
Labels: 🕑 等待合并

#891 feat(ci): 支持自动化 changelog
  .github/workflows/release-beta_publish.yml
  .github/workflows/release-stable_publish.yml
  changelogithub.config.json
Labels: 🕑 等待合并

#842 fix(auto-install): 版本修改相关修复
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionInstall.xaml.vb
Labels: 🕑 等待合并

#856 重新同步代码
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModWatcher.vb
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadShader.xaml
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml.vb
Labels: 🕑 等待合并

#875 feat:游戏版本搜索
  Plain Craft Launcher 2/Pages/PageSelectRight.xaml
  Plain Craft Launcher 2/Pages/PageSelectRight.xaml.vb
Labels: 🕑 等待合并

#910 fix(theme): 正版登录提示框阴影颜色有误
  Plain Craft Launcher 2/Pages/PageLaunch/MyMsgLogin.xaml
Labels: 🕑 等待合并

#947 feat(profile): 自适应档案选择视图大小
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfile.xaml
Labels: 🕑 等待合并

#959 feat: 添加投影原理图支持并优化组件管理功能
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLocalComp.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionLeft.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionLeft.xaml.vb
Labels: 🚧 正在处理

#841 feat(modpack): MMC JSON-Patches 支持
  Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
Labels: 🕑 等待合并

#929 feat(World): 存档版本识别功能
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModWorld.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🚧 正在处理

#973 feat:是否允许作弊和游戏时长获取
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSaves/PageVersionSavesInfo.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSaves/PageVersionSavesInfo.xaml.vb
Labels: 🕑 等待合并

#977 fix:1.8以下的版本没有difficulty导致报错
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSaves/PageVersionSavesInfo.xaml.vb
Labels: 🕑 等待合并
