Repository PCL-Community/PCL2-CE, pull requests merged in 2025-03, with the labels that each got.

#329 feat(CompFav): 允许给收藏夹内的项目加入备注
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
Labels: 🕑 等待合并

#328 feat(CompResource): 基于 ID 的简单查重
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml.vb
Labels: 🕑 等待合并

#323 perf(Proxy): Modify the text of the logging
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
Labels: 🕑 等待合并, 🕑 等待前置

#336 release(fr): 2.10.4 362
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
Labels: 👌 完成

#341 2.10.4 362 hotfix
  Plain Craft Launcher 2/FormMain.xaml
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
  Plain Craft Launcher 2/Modules/ModLink.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkNetStatus.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLink.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLink.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
  README.md
Labels: 👌 完成

#345 fix(GameLog): 修复实时游戏日志在浅色模式下不正常
  Plain Craft Launcher 2/Application.xaml
  Plain Craft Launcher 2/Modules/Minecraft/ModWatcher.vb
Labels: 🕑 等待合并

#346 fix(Update): 判断是否需要更新逻辑有误
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
Labels: 🕑 等待合并

#202 chore(ui): 同步光影和资源包下载页面版本预设项
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadResourcePack.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadShader.xaml
Labels: 🚧 正在处理

#380 feat(CompExportInfo): 允许导出资源信息
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml.vb
Labels: 🕑 等待合并

#354 docs(README.md): README 优化
  README.md
Labels: 🕑 等待合并

#357 杂项: Issue 自动处理
  .github/workflows/issue-closed.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/issue-reopened.yml
Labels: 🕑 等待合并

#382 fix(ResourcesSort): use case-insensitive comparison
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml.vb
Labels: 🕑 等待合并
