Repository PCL-Community/PCL2-CE, pull requests merged in 2025-09, with the labels that each got.

#1507 feat(Comp): 显示可选的前置模组
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
Labels: 🕑 等待合并, size: L

#1504 fix(crash-analyzer): 修复 Quilt 堆栈分析可能意外纳入信息的问题
  Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
Labels: 🕑 等待合并, size: S

#1387 refactor(net): 重构 CE 的部分网络库到 Core
  PCL.Test/DiffTest.cs
  PCL.Test/JavaTest.cs
  PCL.Test/PCL.Test.csproj
  PCL.Test/WebServerTest.cs
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Controls/MyImage.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/ModLink.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Modules/ModWebServer.vb
  Plain Craft Launcher 2/Modules/Updates/UpdatesMinioModel.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginAuth.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherVote.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupJava.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🛠️ 等待审查, size: XL

#1506 feat(comp): 支持选择资源搜索排序方式
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageComp.xaml
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageComp.xaml.vb
Labels: 🕑 等待合并, size: L

#1565 feat(launch): 支持全局设置游戏渲染器，并将警告提示改为弹窗
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSetup.xaml
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSetup.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
Labels: 🛠️ 等待审查, size: M

#1570 ref: 同步 Core 代码修改
  PCL.Test/EncodingDetectorTest.cs
  PCL.Test/JavaTest.cs
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceOverall.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSetup.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherLog.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupJava.xaml.vb
Labels: 🕑 等待合并, size: M
