Repository PCL-Community/PCL2-CE, pull requests merged in 2025-02, with the labels that each got.

#155 创建一些管理 Issues 和 PR 的 GitHub Actions
  .github/workflows/issue-close.yml
  .github/workflows/labels.yml
  .github/workflows/pr.yml
Labels: 🕑 等待合并

#168 修复一些剪贴板资源识别相关的 Bug
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
Labels: 🕑 等待合并

#169 调整个性化设置中的一些 UI 细节
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
Labels: 🕑 等待合并

#174 fix: 深色模式 #5
  Plain Craft Launcher 2/Controls/MyCard.vb
  Plain Craft Launcher 2/Controls/MyHint.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/MyLocalModItem.xaml.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: 🕑 等待合并

#177 fix: button not display well
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml
Labels: 👌 完成

#178 fix: incorrect value
  Plain Craft Launcher 2/Pages/PageLaunch/MyMsgLogin.xaml
Labels: 🕑 等待合并

#180 剪贴板修复与部分 UI 调整
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml
Labels: 🕑 等待合并

#181 bump: 2.10.0
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/My Project/AssemblyInfo.vb
Labels: 👌 完成

#192 chore(ui): 文本优化
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionInstall.xaml
Labels: 🚧 正在处理, 🕑 等待合并

#198 fix: 版本设置 Java Wrapper 设置不生效
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml.vb
Labels: 👌 完成

#204 fix: select logic error
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
Labels: 🕑 等待合并

#208 Fix:第三方登录 Bug
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 👌 完成

#205 feat: new application icon
  Plain Craft Launcher 2/Images/icon.ico
Labels: 🕑 等待合并

#214 修正模板描述
  .github/ISSUE_TEMPLATE/bug2.yml
  .github/ISSUE_TEMPLATE/bug9.yml
Labels: 🕑 等待合并

#213 feat: issue template 添加官方版引用
  .github/ISSUE_TEMPLATE/ch.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: 🕑 等待合并

#219 Feat:优化 Actions 文件
  .github/workflows/build.yml
Labels: 🕑 等待合并

#207 fix: 深色模式 #7
  Plain Craft Launcher 2/Controls/MyHint.xaml.vb
Labels: 🕑 等待合并

#224 fix #216
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionInstall.xaml.vb
Labels: 🕑 等待合并

#229 improve: allow refresh
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherFeedback.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherLeft.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherVote.xaml.vb
Labels: 🕑 等待合并

#231 improve: reduce some warnings
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionScreenshot.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🕑 等待合并

#225 优化：静默更新和更新提示
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: 🕑 等待合并

#239 2.10.3
  .github/workflows/build.yml
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
Labels: 🕑 等待合并

#250 fix: potential exception throw
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionResourcePack.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionShader.xaml.vb
Labels: 🕑 等待合并

#251 text: 文本调整
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
Labels: 👌 完成

#255 Fix:硬编码导致编译问题&Self-hosted Runner 不会自动清理文件导致编译失败
  .github/workflows/build.yml
Labels: 🕑 等待合并

#267 fix: install function not work
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
Labels: 🕑 等待合并

#268 fix(log): 修复部分地方使用原版日志的问题
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModWatcher.vb
  Plain Craft Launcher 2/Resources/Custom.xaml
Labels: 🕑 等待合并

#271 fix: are u sure about that????
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
Labels: 🕑 等待合并

#242 通过接入MCIM API以支持简介翻译
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
Labels: 🚧 正在处理

#274 fix: mistake share webplib with official
  Plain Craft Launcher 2/Application.xaml.vb
Labels: 🕑 等待合并

#249 升级：多收藏夹&允许分享&批量下载
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
  Plain Craft Launcher 2/Pages/PageSelectLeft.xaml.vb
Labels: 🕑 等待合并

#286 fix: 排序花费太多时间
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml.vb
Labels: 🕑 等待合并

#292 feat: 内存优化
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
Labels: 🚧 正在处理

#299 feat(Comp)!: 修改本地资源展现的实现方式
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLocalComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/MyCompItem.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/MyLocalCompItem.xaml
  Plain Craft Launcher 2/Modules/Minecraft/MyLocalCompItem.xaml.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadMod.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionCompResource.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionResourcePack.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionResourcePack.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionShader.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionShader.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🕑 等待合并, ❗ 破坏性

#287 自动安装相关改进
  Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionInstall.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionOverall.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionOverall.xaml.vb
Labels: 👌 完成

#315 fix: treat cleanroom instances as installable mods
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
Labels: 🚧 正在处理

#321 fix(ShowLog): 特定版本没有匹配
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
Labels: 🕑 等待合并

#324 perf(Feedback): 打开网页后关闭弹窗
  Plain Craft Launcher 2/Pages/PageOther/PageOtherFeedback.xaml.vb
Labels: 🕑 等待合并
