Repository PCL-Community/PCL2-CE, pull requests merged in 2025-08, with the labels that each got.

#1240 perf(CompResource): RawPath是对的，使用HashSet代替List
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceCompResource.xaml.vb
Labels: 🕑 等待合并

#1225 feat(Link): 更新 EasyTier 到 2.4.0 并支持 ACL
  Plain Craft Launcher 2/Modules/ModLink.vb
Labels: 🕑 等待合并

#1245 feat(Comp): 收藏夹加入世界资源分类
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
Labels: 🛠️ 等待审查, XS

#1243 bump: 2.12.0-beta.14
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
Labels: 🕑 等待合并, XS

#1246 feat(MyCheckBox): 复选框的三态
  Plain Craft Launcher 2/Controls/MyCheckBox.xaml
  Plain Craft Launcher 2/Controls/MyCheckBox.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
Labels: 🕑 等待合并

#1247 feat(Link): 更新 EasyTier 至 2.4.1
  Plain Craft Launcher 2/Modules/ModLink.vb
Labels: 🕑 等待合并

#1252 fix(FormMain): 二次修复更新公告显示问题
  Plain Craft Launcher 2/FormMain.xaml.vb
Labels: 🕑 等待合并

#1273 imp(OtherTest): 使百宝箱按钮自动换行
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
Labels: 🕑 等待合并

#1285 imp(Link): 改进陶瓦用户信息的显示效果
  Plain Craft Launcher 2/Modules/ModLink.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml.vb
Labels: 🕑 等待合并

#1300 imp: 移除单例检查
  Plain Craft Launcher 2/Application.xaml.vb
Labels: 🕑 等待合并

#1296 fix(link): 可能因为一些信息未能获取到错误地判定大厅不存在
  Plain Craft Launcher 2/Modules/ModLink.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml.vb
Labels: 🕑 等待合并

#1304 fix(link): 输出重定向导致的 ET 在部分情况下卡住
  Plain Craft Launcher 2/Modules/ModLink.vb
Labels: 🕑 等待合并

#1293 style: 一个巨大的 typo 修复
  Plain Craft Launcher 2/Controls/MyCard.vb
  Plain Craft Launcher 2/Pages/PageDownload/Comp/MyCompItem.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCleanroom.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadForge.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLiteLoader.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadNeoForge.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadOptiFine.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceExport.xaml
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceInstall.xaml
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceInstall.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSetup.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherFeedback.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherHelp.xaml.vb
  Plain Craft Launcher 2/Pages/PageSelectRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageHomePageMarket.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Resources/Custom.xaml
Labels: 🕑 等待合并

#1274 feat(MinecraftServer): 独立的 Minecraft 服务器查询控件
  Plain Craft Launcher 2/Controls/MinecraftServer.xaml
  Plain Craft Launcher 2/Controls/MinecraftServer.xaml.vb
  Plain Craft Launcher 2/Controls/MinecraftServerQuery.xaml
  Plain Craft Launcher 2/Controls/MinecraftServerQuery.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🕑 等待合并

#1251 feat(SelectLeft): 添加文件夹列表排序
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Pages/PageSelectLeft.xaml.vb
Labels: 🕑 等待合并

#1302 style: PageOtherFeedback.xaml.vb下部分符号错误问题
  Plain Craft Launcher 2/Pages/PageOther/PageOtherFeedback.xaml.vb
Labels: 🕑 等待合并

#1307 fix(Instance): 修复官方启动器文件夹类型判断错误
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Pages/PageSelectLeft.xaml.vb
Labels: 🕑 等待合并

#1311 feat(ShaderPack): 可单独选择光影加载器
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageComp.xaml
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageComp.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadShader.xaml
Labels: 🕑 等待合并

#1315 fix(instance-install): 修复 (Legacy) Fabric API 的选择框下端间隔不正常
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceInstall.xaml
Labels: 🕑 等待合并

#1308 fix(link): 连接到陶瓦用户的大厅时部分文本显示异常
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml.vb
Labels: 🕑 等待合并

#1268 perf(SavesInfo): 加入存档信息缓存
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSaves/PageInstanceSavesInfo.xaml.vb
Labels: 🛠️ 等待审查, size: XL

#1325 feat(link): 更换 QA 页面
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkQA.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkQA.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 🕑 等待合并

#1328 feat(link): 允许在有多个 ET 实例的情况下与正确的 ET 实例通讯
  Plain Craft Launcher 2/Modules/ModLink.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml.vb
Labels: 🕑 等待合并

#1329 imp(path): 检测社交软件下载目录并给予警告
  Plain Craft Launcher 2/Application.xaml.vb
Labels: 🕑 等待合并

#1313 refactor(Setup): 迁移配置系统
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceOverall.xaml.vb
  Plain Craft Launcher 2/Pages/PageSelectRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
Labels: 🕑 等待合并

#1339 Legacy Fabric 手动安装页面文案优化
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLegacyFabric.xaml
Labels: 🕑 等待合并, size: XS

#1349 refactor(setup): 迁移 SystemSystemUpdateBranch
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
Labels: 🕑 等待合并, size: XS

#1359 imp(mod-modpack): 优化加密整合包错误提示
  Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
Labels: 🕑 等待合并, size: XS

#1366 feat: 支持修改渲染器
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSetup.xaml
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSetup.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml
Labels: 🕑 等待合并, size: L

#1381 refactor(link): 重构联机页面布局
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml.vb
Labels: 🕑 等待合并, size: XL

#1380 feat(http-proxy): 修复 HTTP 代理的一堆问题
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
Labels: 🕑 等待合并, size: L

#1373 fix: 修复资源下载界面收藏按钮行为异常
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Pages/PageDownload/Comp/MyCompItem.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadCompDetail.xaml.vb
Labels: 🕑 等待合并, size: M

#1405 refactor: 使用更现代的 API
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Controls/MyResizer.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Base/ModValidate.vb
  Plain Craft Launcher 2/Modules/Base/MyBitmap.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLocalComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/ModLink.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/My Project/Application.myapp
  Plain Craft Launcher 2/My Project/AssemblyInfo.vb
  Plain Craft Launcher 2/My Project/MyExtensions/MyWpfExtension.vb
  Plain Craft Launcher 2/My Project/Resources.Designer.vb
  Plain Craft Launcher 2/My Project/Resources.resx
  Plain Craft Launcher 2/My Project/Settings.Designer.vb
  Plain Craft Launcher 2/My Project/Settings.settings
  Plain Craft Launcher 2/My Project/app.manifest
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceCompResource.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceLeft.xaml
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceOverall.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSaves.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSaves/PageInstanceSavesLeft.xaml
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSaves/PageInstanceSavesLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceScreenshot.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSetup.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfileSkin.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginProfileSkin.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
  Plain Craft Launcher 2/Pages/PageSelectRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
Labels: 🕑 等待合并, size: XXL

#1418 improve: update-help
  .github/workflows/update-help.yaml
Labels: 🕑 等待合并, size: XS

#1367 feat(other-test): 加入自定义成就图片生成器
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
Labels: 🕑 等待合并, size: L

#1436 refactor: 使用基于代码生成优化的正则表达式
  Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginAuth.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherLog.xaml.vb
Labels: 🕑 等待合并, size: S

#1440 fix(ui): 将窗口大小加载提前
  Plain Craft Launcher 2/FormMain.xaml.vb
Labels: 🕑 等待合并, size: S

#1441 imp(backgroud): 修改加载视频失败时给出的错误提示
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
Labels: 🕑 等待合并, size: M

#1445 fix(ui): 修复字体下拉框无法响应宽度更改
  Plain Craft Launcher 2/Controls/MyComboBox.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
Labels: 🕑 等待合并, size: L

#1451 fix(assets-get): 修复资源下载补全问题
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
Labels: 🕑 等待合并, size: S

#1449 fix(ui): 修复主窗体为隐藏状态时激活不生效
  Plain Craft Launcher 2/FormMain.xaml.vb
Labels: 🕑 等待合并, size: XS

#1458 fix(authlib): 补充修复第三方验证登录时无法选择角色的问题
  Plain Craft Launcher 2/Modules/Minecraft/ModProfile.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchLeft.xaml.vb
Labels: 🕑 等待合并, size: S

#1404 feat: 加入实例设置-服务器栏
  Plain Craft Launcher 2/Controls/MinecraftServer.xaml.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceLeft.xaml
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceScreenshot.xaml
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceServer.xaml
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceServer.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/ServerCard.xaml
  Plain Craft Launcher 2/Pages/PageInstance/ServerCard.xaml.vb
Labels: 🕑 等待合并, size: XL

#1468 ci: 支持自动更新 Release discussion 的正文
  .github/workflows/release-beta_publish.yml
  .github/workflows/release-stable_publish.yml
  .github/workflows/update-release-discussion.yml
Labels: 🕑 等待合并, size: L

#1474 ref: 使用 Core 代码
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Controls/MyImage.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModAnimation.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Base/ModLoader.vb
  Plain Craft Launcher 2/Modules/Base/ModNativeInterop.vb
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLocalComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModProfile.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModWorld.vb
  Plain Craft Launcher 2/Modules/ModLink.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Modules/ModMusic.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Modules/Updates/UpdatesMinioModel.vb
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/MyLocalModItem.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceCompResource.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceExport.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceOverall.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSaves/PageInstanceSavesBackup.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLobby.xaml.vb
  Plain Craft Launcher 2/Pages/PageLogRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherFeedback.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherLog.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
  Plain Craft Launcher 2/Pages/PageSelectLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupJava.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
  Plain Craft Launcher 2/Pages/PageSpeedLeft.xaml.vb
Labels: 🕑 等待合并, size: XL

#1480 refactor: 替换部分全局路径变量
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Base/ModNativeInterop.vb
  Plain Craft Launcher 2/Modules/Base/ModSetup.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModWatcher.vb
  Plain Craft Launcher 2/Modules/ModEvent.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Modules/ModMusic.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Modules/Updates/UpdatesMinioModel.vb
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceExport.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSaves/PageInstanceSavesBackup.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceScreenshot.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
  Plain Craft Launcher 2/Pages/PageSelectLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
Labels: 🕑 等待合并, size: L

#1492 ref: 同步 Core 方法修改
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceCompResource.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceExport.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceOverall.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceSaves/PageInstanceSavesBackup.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/PageInstanceServer.xaml.vb
  Plain Craft Launcher 2/Pages/PageInstance/ServerCard.xaml.vb
  Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
  Plain Craft Launcher 2/Pages/PageLogRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherLog.xaml.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
  Plain Craft Launcher 2/Pages/PageSelectLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupJava.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
Labels: 🕑 等待合并, size: L

#1494 fix(mainpage): 部分预设自定义主页链接未同步上游
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml.vb
Labels: 🕑 等待合并, size: XS

#1478 fix(environment): 不再检测 .NET Framework 环境；系统版本要求降低到 17763
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
Labels: 🕑 等待合并, size: M

#1491 fix(ui): 修复字体重复初始化时出错
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
Labels: 🕑 等待合并, size: M

#1503 fix(launch): 解决 Java 版本要求可能不正确的问题
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 🕑 等待合并, size: M

#1505 fix(setup): 修复动画速度滑动条精度问题
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
Labels: 🕑 等待合并, size: XS
